CREATE TABLE ACTOR(
    ACT_ID VARCHAR(20),
    ACT_NAME VARCHAR(20),
    ACT_GENDER INT,
    PRIMARY KEY(ACT_ID)
);

CREATE TABLE DIRECTOR(
    DIR_ID VARCHAR(20),
    DIR_NAME VARCHAR(20),
    DIR_PHONE VARCHAR(10),
    PRIMARY KEY(DIR_ID)
);


CREATE TABLE MOVIE(
    DIR_ID VARCHAR(20),
    MOV_ID VARCHAR(20),
    MOV_TITLE VARCHAR(20),
    MOV_YEAR DATE,
    MOV_LANG VARCHAR(20),
    PRIMARY KEY(MOV_ID),
    FOREIGN KEY(DIR_ID) REFERENCES DIRECTOR(DIR_ID)
);


CREATE TABLE MOVIE_CAST(
    ACT_ID VARCHAR(20), 
    MOV_ID VARCHAR(20), 
    ROLE VARCHAR(20),
    PRIMARY KEY(ROLE),
    FOREIGN KEY(ACT_ID) REFERENCES ACTOR(ACT_ID),
    FOREIGN KEY(MOV_ID) REFERENCES MOVIE(MOV_ID)
);

CREATE TABLE RATING(
    MOV_ID VARCHAR(20),
    REV_STARS INT,
    PRIMARY KEY(MOV_ID),
    FOREIGN KEY(MOV_ID) REFERENCES MOVIE(MOV_ID)
);
DESC ACTOR;
INSERT INTO ACTOR VALUES('&ACT_ID', '&ACT_NAME', &ACT_GENDER);
-- DELETE FROM ACTOR WHERE ACT_ID = '1';
SELECT * FROM ACTOR;

DESC DIRECTOR;
INSERT INTO DIRECTOR VALUES('&DIR_ID', '&DIR_NAME', '&DIR_PHONE');
SELECT * FROM DIRECTOR;

DESC MOVIE;
INSERT INTO MOVIE VALUES('&DIR_ID', '&MOV_ID', '&MOV_TITLE', '&MOV_YEAR', '&MOV_LANG');
SELECT * FROM MOVIE;

INSERT INTO MOVIE_CAST VALUES('&ACT_ID', '&MOV_ID', '&ROLE');
SELECT * FROM MOVIE_CAST;

INSERT INTO RATING VALUES('&MOV_ID', &REV_STARS);
SELECT * FROM RATING;




 --List the titles of all movies directed by ‘Hitchcock’.
 SELECT MOV_TITLE FROM MOVIE, DIRECTOR
 WHERE MOVIE.DIR_ID = DIRECTOR.DIR_ID AND DIRECTOR.DIR_NAME = 'HITCHKOK';
 
 
 -- Find the title of movies and number of stars for each movie that has at least one 
 --rating and find the highest number of stars that movie received. Sort the result by movie title. 
 
 