CREATE TABLE STUDENT(
    SNUM INT,
    SNAME VARCHAR(30),
    MAJOR VARCHAR(30),
    LVL VARCHAR(30),
    AGE INT,
    PRIMARY KEY(SNUM)
);
DESC STUDENT;

CREATE TABLE CLASS(
    -- CNAME IS CLASS NAME , FID IS CLASS TEACHER
    CNAME VARCHAR(30),
    MEETSAT TIMESTAMP,
    ROOM VARCHAR(30),
    FID INT,
    PRIMARY KEY(CNAME),
    FOREIGN KEY(FID) REFERENCES FACULTY(FID)
);
DESC CLASS;

CREATE TABLE ENROLLED(
    SNUM INT,
    CNAME VARCHAR(30),
    PRIMARY KEY(SNUM),
    FOREIGN KEY(SNUM) REFERENCES STUDENT(SNUM),
    FOREIGN KEY(CNAME)REFERENCES CLASS(CNAME)
);
DESC ENROLLED;

CREATE TABLE FACULTY(
    FID INT,
    FNAME VARCHAR(30),
    DEPTID INT,
    PRIMARY KEY(FID)
);

FR SO JR SR

INSERT INTO STUDENT VALUES(&SNUM, '&SNAME', '&MAJOR', '&LVL', &AGE);
SELECT * FROM STUDENT;

INSERT INTO FACULTY VALUES(&FID, '&FNAME', &DEPTID);
SELECT * FROM FACULTY;

INSERT INTO CLASS VALUES('&CNAME', '&MEETSAT', '&ROOM', &FID);
SELECT * FROM CLASS;

INSERT INTO ENROLLED VALUES(&SNUM, '&CNAME');
SELECT * FROM ENROLLED;

COMMIT;


SELECT DISTINCT SNAME FROM FACULTY, CLASS, ENROLLED, STUDENT
WHERE STUDENT.LVL = 'JR' AND FACULTY.FNAME = 'ABC' AND CLASS.CNAME = ENROLLED.CNAME;

